service: my-slackbot
provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  iamRoleStatements:
  - Effect: "Allow"
    Action:
    - "dynamodb:*"
    Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"

functions:
  saveUserStandupResponse:
    handler: saverecord.saveUserStandupResponse
    events:
      - http:
          path: saveUserStandupResponse
          method: post
          cors: true